### ISSUE TITLE
boolean value (true , false) in the table is converted into 1 character of 't' or 'f'

### ISSUE THREAD

**Issue by jetulis** [Aternus/csv-to-xlsx#10]
I see boolean value becoming 't' or 'f' , rather than true , false . 
![image](https://user-images.githubusercontent.com/10562/91315258-7b171b80-e785-11ea-9c91-9ae29e83815f.png)

**Comment by Aternus** [comment]
Hey @jetulis , could you provide source input and expected output?

**Comment by Aternus** [comment]
FYI, I've added a simple test which passed correctly, so I'll need the source file to see what makes it unique.
