### ISSUE TITLE
Convert specific file

### ISSUE THREAD

**Issue by kakadais** [Aternus/csv-to-xlsx#11]
It works great- 
This converts a leading zero to xlsx with text, lovely.

But I need to make a directory to convert a specific file if there are other csv files.

I think that's a reasonable functionality on cli command as well-

**Comment by Aternus** [comment]
Hey @kakadais , I'm not sure what you mean...
Kindly provide an example of input and expected output for what you want to do...

**Comment by kakadais** [comment]
@Aternus Sorry for rough request-

The API looks like specify the file name,
```let source = path.join(__dirname, 'report.csv');```

But CLI tool seems to convert only all csv file in the directory.
```npx csv-to-xlsx -i "input-directory" -o "output-directory"```

So it could be great if CLI tool could be specify a file conversion.

* Sorry if I miss something although there's a same option already-, I can't find it-

**Comment by Aternus** [comment]
Thank you, now I get it. Kindly open a feature request and we'll see what we can do about it. 
I'd prefer not to break the current command line syntax so that anyone who is using this won't have to rewrite their code.

**Comment by kakadais** [comment]
Cool- 
I love your syntax such as if we miss -o option then use the same path at -i.

I suggest use the same option.
Which means, if the path is directory then works same,
if the path is file then works just that file.

Thanks-

**Comment by Aternus** [comment]
Added in v2.1.0
