### ISSUE TITLE
importing module in Angular

### ISSUE THREAD

**Issue by devtechk** [Aternus/csv-to-xlsx#12]
Hi, thank you for this great feature. 
I'm just trying to use it in Angular8 importing in this way  import { convertCsvToXlsx } from '@aternus/csv-to-xlsx'; 
after the package has been installed.
The fact is that i run into this problem: 

![image](https://user-images.githubusercontent.com/22073497/106018434-cc736000-60c1-11eb-8285-48064fa655c7.png)

Do you have any solution?

Thank you!

**Comment by Aternus** [comment]
Hey @devtechk , please kindly provide a code sandbox with the use case you're describing so I can investigate. I'm not familiar with Angular8 so I'll need this to move forward. Thank you.

https://codesandbox.io/

**Comment by Aternus** [comment]
Closed due to lack of author response.
