### ISSUE TITLE
Feature Request - customizable delimiter

### ISSUE THREAD

**Issue by cnniss** [Aternus/csv-to-xlsx#27]
The delimiter for CSV is a hardcoded "," - unfortunately with German language context that won't work as "," is the decimal separator in numbers.
It would be cool if one could specify the delimiter on the function call.

**Comment by Aternus** [comment]
Hey @cnniss 👋 
The CSV standard uses double quotes for escaping values that have commas, you'll need to normalize your data before performing the conversion.

Example:
```csv
item name,price
some kind of name,"10,99"
```

**Comment by cnniss** [comment]
sorry, that won't work because values within quotes are treated as string - not as number.

I have source CSV like
Key;value
234234;12,15
34343;55,34

12,15 is a float number as well as 55,34 (american notation 12.15 and 55.34

In the German and most European language contexts the comma is the decimal separator.
";" is the common CSV delimiter in the German speaking world - that's how I get the data from the client.
When I normalize like you suggest the numbers become strings in the resulting Excel - Hence not processable by the other client that needs to import the Excel data.

That's why the delimiter should be configurable as option rather than being hardcoded. It would be very cool if the tool supported this.

**Comment by cnniss** [comment]
and if I convert the excel by replacing the European column separator ";" with "," and the European "," with "." Excel in German and other European language versions would not recognize that as a number beacuse it's expecting numbers to have a comma as decimal separator like in the installed language context.

So this request is not something specific for me but a solution to make the library useable in Europe with Europan languag context.

Many thanks in advance.

**Comment by cnniss** [comment]
Hi,
I have attached a source csv and the expexted excel result.

[excelresult.xlsx](https://github.com/Aternus/csv-to-xlsx/files/14292561/excelresult.xlsx)
[csvsource.csv](https://github.com/Aternus/csv-to-xlsx/files/14292562/csvsource.csv)

Well the issue is a country locale issue. whenever you export a csv file from a comupter that is running under German/Italien/Spanish/French language setup the resulting CSV will have ";" as separator sign. All numbers will be formated with a "," as decimal separator. That's the way how numbers are formated in Europe and probably other parts of the world.

You can't switch the language context in Excel - it's an OS issue that defines the language locales.

This is how an Excel sheet looks like in German language Excel
<img width="265" alt="Bildschirmfoto 2024-02-15 um 08 03 46" src="https://github.com/Aternus/csv-to-xlsx/assets/109089901/9ed8dcbe-f734-431d-8bcd-f8cb4412458d">

In case I normalize the excel like you suggested (convert separators to "," and put column values in double quotes I end up with an excel sheet that imports the quoted numbers as strings - hence not useable for calculations. 
<img width="257" alt="Bildschirmfoto 2024-02-15 um 08 09 33" src="https://github.com/Aternus/csv-to-xlsx/assets/109089901/ecbe2fe1-5cc7-47bb-a011-44a121fc5c4e">

HTH
CHris
