### ISSUE TITLE
Some specific delimiter expected?

### ISSUE THREAD

**Issue by greenais** [Aternus/csv-to-xlsx#6]
Tried you lib on test file in npx and node mode and got the same error:
`Error: Invalid Record Length: columns length is 1, got 4 on line 8`

The thing is that all lines have same format (including header one), why only line 8?

Here is my test csv excerpt:
``key;English;Русский;Беларуская

ad;Advertisement;Объявление;XXX

back;Back;Назад;XXX

category;Category;Категория;XXX

cities;Cities;Города;XXX

class;Class;Урок;XXX

compose;Compose advertisement;Создание объявления;XXX

contactSupport;In case error persists, please contact our;В случае, если ошибка сохранится, обратитесь в нашу;XXX

copy;Copy;Копия;XXX

dearClient;Dear customer;Уважаемый клиент;XXX

discount;Discount;Скидка;XXX``

**Comment by Aternus** [comment]
Hey Alexander,

Looks like you're trying to parse a semi-colon separated file (i.e. `;`) and not CSV (i.e. `,`)

**Comment by greenais** [comment]
Yep, I'm. 
Sorry for disturbing then, not suitable for my needs. Tnx.
