### ISSUE TITLE
Error reading xlsx file when Excel is configured with another country format

### ISSUE THREAD

**Issue by esvanegas** [Aternus/csv-to-xlsx#8]
I'm using the csv-to-xlsx library to replace an old bash script, I'm from a country where '**,**' is used to place decimals.

The issue is that when I convert the xlsx with number columns, it automatically changes to '**.**' any kind of number.

Eg.

Original Column: 42
Result Column: 42.00

This causes that when the file is opened in excel with another country format, the number columns can't be placed as number columns only text columns.

**Comment by Aternus** [comment]
Can you provide a sample input file and an expected output file together
with instructions to reproduce the issue?

**Comment by esvanegas** [comment]
Due to GitHub doesn't support csv and xlsx file types, so I uploaded to this [dropbox folder](https://www.dropbox.com/sh/zh983nsgq5fkos6/AADDo6M7VLC3w_GPLA6aTil0a?dl=0). There you could find thre files:

- **input.csv:** This file is the input csv file
- **result.xlsx:** This file is the result file using the following code
- **expectedResult.xlsx:** This file is the expected result

You can reproduce the error running the following code.

```javascript
"use strict";
const fs = require('fs');
const convertCsvToXlsx = require('@aternus/csv-to-xlsx');


/**
 * Convert csv to xslsx
 * 
 * Verifies if csvPath exists, then verifies if xlsxPath exists, if xlsx path exists, it is going to
 * delete the path to proceed to csv to xlsx conversion to specified path.
 * 
 * @param {String} csvPath                  - CSV file path
 * @param {String} xlsxDestinationPath      - XLSX file path
 * @returns {Boolean}                       - Convert successfully or not
 */
async function to_xlsx(csvPath,xlsxDestinationPath){
    let csvExists = await file_exists(csvPath);
    if(csvExists){
        let xlsxExists =await file_exists(xlsxDestinationPath);
        if(xlsxExists) await delete_file(xlsxDestinationPath); 
        try{
            convertCsvToXlsx(csvPath, xlsxDestinationPath);
            return true;
        }catch(e){
            mailLogger.error('error converting to xlsx',e);
            return false;
        }
    }
}

/**
 * Check if a file exists
 * 
 * @param {String} path     - File path to check
 * @returns {Promise}       - File path exists or not promise
 */
async function file_exists(path){
    return new Promise((resolve,reject)=>{
        fs.access(path,fs.F_OK,(err)=>{
            if(err){
                resolve(false);
            }
            resolve(true);
        });
    });
}

/**
 * Delete a file
 * 
 * @param {String} path     - File path to delete
 * @returns {Promise}       - Delete file path promise
 */
async function delete_file(path){
    return new Promise((resolve,reject)=>{
        fs.unlink(path, (err)=>{
            if(err){
                reject(undefined);
            }
            resolve(true);
        })
    });
}
```

To execute the code just add at the end of the code:
```javascript
let csvPath= ******;  //input.csv file path
let xlsxPath= ******; //xlsx file path
to_xlsx(csvPath, xlsxPath).then((result)=>{console.log(result});
```

**Comment by Aternus** [comment]
Please try the newest version and let me know if it works for you; I've used your file as input and it worked correctly.

**Comment by esvanegas** [comment]
It looks like the expected file but, no format can be applied, unless you double click each cell or in case, edit it.

![image](https://user-images.githubusercontent.com/44588624/88345553-ca43d980-cd0b-11ea-938f-b7f85a095d78.png)

For example

Resulting xlsx

![image](https://user-images.githubusercontent.com/44588624/88345752-4807e500-cd0c-11ea-8a5c-a637a179d991.png)


Double click into cells

![image](https://user-images.githubusercontent.com/44588624/88345684-1db62780-cd0c-11ea-87d8-1d8755ceba60.png)

When double click is applied I can change the number format, otherwise not.

**Comment by Aternus** [comment]
The cells are of "General" format on purpose, that's a limitation of Excel.

However, you can achieve what you want to do by:
1. Selecting all the cells with numbers
2. Copy-paste the cells into the same location
3. A pop-up will appear at the top right suggesting to convert to numbers, select that option
4. After Excel finishes converting the values you'll be able to work with them as numbers/currency
